"""SQLAlchemy models for the trading system database."""

from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, DateTime, Text, ForeignKey, JSON
from sqlalchemy.orm import relationship
from database.connection import Base


class MarketData(Base):
    """Market OHLC price data."""

    __tablename__ = 'market_data'

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(10), nullable=False, index=True)
    timeframe = Column(String(10), nullable=False, default='1d')
    timestamp = Column(DateTime, nullable=False, index=True)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Integer)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    indicators = relationship('Indicator', back_populates='market_data', cascade='all, delete-orphan')

    __table_args__ = (
        # Unique constraint on symbol, timeframe, timestamp
        {'sqlite_autoincrement': True},
    )

    def __repr__(self):
        return f"<MarketData(symbol='{self.symbol}', timestamp='{self.timestamp}', close={self.close})>"


class Indicator(Base):
    """Technical indicators calculated from market data."""

    __tablename__ = 'indicators'

    id = Column(Integer, primary_key=True, autoincrement=True)
    market_data_id = Column(Integer, ForeignKey('market_data.id'), nullable=False)
    symbol = Column(String(10), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    ema_20 = Column(Float)
    ema_50 = Column(Float)
    rsi_14 = Column(Float)
    atr_14 = Column(Float)
    swing_low = Column(Float)
    swing_high = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    market_data = relationship('MarketData', back_populates='indicators')

    def __repr__(self):
        return f"<Indicator(symbol='{self.symbol}', timestamp='{self.timestamp}')>"


class Signal(Base):
    """Trading signals generated by the strategy."""

    __tablename__ = 'signals'

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(10), nullable=False, index=True)
    signal_date = Column(DateTime, nullable=False, index=True)
    signal_type = Column(String(10), nullable=False)  # BUY, SELL
    entry_price = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    take_profit = Column(Float, nullable=False)
    sl_pips = Column(Float)
    tp_pips = Column(Float)
    risk_reward_ratio = Column(Float)
    confidence_score = Column(Float)  # Optional: 0-100
    reasoning = Column(Text)
    status = Column(String(20), default='PENDING')  # PENDING, EXECUTED, SKIPPED
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    backtest_trades = relationship('BacktestTrade', back_populates='signal')
    live_trades = relationship('LiveTrade', back_populates='signal')

    def __repr__(self):
        return f"<Signal(symbol='{self.symbol}', type='{self.signal_type}', date='{self.signal_date}')>"


class BacktestTrade(Base):
    """Historical backtest trade results."""

    __tablename__ = 'backtest_trades'

    id = Column(Integer, primary_key=True, autoincrement=True)
    backtest_run_id = Column(Integer, ForeignKey('backtest_runs.id'))
    signal_id = Column(Integer, ForeignKey('signals.id'))
    symbol = Column(String(10), nullable=False, index=True)
    direction = Column(String(10), nullable=False)  # LONG, SHORT
    entry_date = Column(DateTime, nullable=False)
    entry_price = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    take_profit = Column(Float, nullable=False)
    exit_date = Column(DateTime)
    exit_price = Column(Float)
    exit_reason = Column(String(20))  # TP_HIT, SL_HIT, MANUAL
    pips = Column(Float)
    profit_loss = Column(Float)
    profit_loss_pct = Column(Float)
    position_size = Column(Float)  # Lot size
    outcome = Column(String(10))  # WIN, LOSS, BREAKEVEN
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    backtest_run = relationship('BacktestRun', back_populates='trades')
    signal = relationship('Signal', back_populates='backtest_trades')

    def __repr__(self):
        return f"<BacktestTrade(symbol='{self.symbol}', outcome='{self.outcome}', pips={self.pips})>"


class BacktestRun(Base):
    """Backtest run metadata and summary statistics."""

    __tablename__ = 'backtest_runs'

    id = Column(Integer, primary_key=True, autoincrement=True)
    run_name = Column(String(100), nullable=False)
    strategy_name = Column(String(100))
    start_date = Column(DateTime, nullable=False)
    end_date = Column(DateTime, nullable=False)
    initial_capital = Column(Float)
    risk_per_trade_pct = Column(Float)
    parameters = Column(JSON)  # Store strategy parameters as JSON
    total_trades = Column(Integer)
    winning_trades = Column(Integer)
    losing_trades = Column(Integer)
    win_rate = Column(Float)
    profit_factor = Column(Float)
    max_drawdown = Column(Float)
    net_profit = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    trades = relationship('BacktestTrade', back_populates='backtest_run', cascade='all, delete-orphan')

    def __repr__(self):
        return f"<BacktestRun(name='{self.run_name}', trades={self.total_trades})>"


class LiveTrade(Base):
    """Live and paper trading records."""

    __tablename__ = 'live_trades'

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(Integer, ForeignKey('signals.id'))
    symbol = Column(String(10), nullable=False, index=True)
    direction = Column(String(10), nullable=False)  # LONG, SHORT
    entry_date = Column(DateTime, nullable=False)
    entry_price = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    take_profit = Column(Float, nullable=False)
    position_size = Column(Float)
    exit_date = Column(DateTime)
    exit_price = Column(Float)
    exit_reason = Column(String(20))
    pips = Column(Float)
    profit_loss = Column(Float)
    outcome = Column(String(10))  # WIN, LOSS, BREAKEVEN
    trade_type = Column(String(10), default='PAPER')  # PAPER, LIVE
    notes = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    signal = relationship('Signal', back_populates='live_trades')

    def __repr__(self):
        return f"<LiveTrade(symbol='{self.symbol}', type='{self.trade_type}', outcome='{self.outcome}')>"
